definitions:
  request.CreateStudentRequest:
    properties:
      born_date:
        type: string
      country_id:
        type: integer
      first_name:
        type: string
      last_name:
        type: string
    type: object
  response.ErrorResponse:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
  response.HealthResponse:
    properties:
      status:
        type: string
    type: object
  response.UserResponse:
    properties:
      born_date:
        type: string
      country_iso:
        type: string
      country_name:
        type: string
      created_at:
        type: string
      first_name:
        type: string
      id:
        type: integer
      last_name:
        type: string
      updated_at:
        type: string
    type: object
info:
  contact: {}
paths:
  /health-check:
    get:
      description: Verify status microservice
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.HealthResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      tags:
      - Health Check
  /student:
    post:
      description: Create Students
      parameters:
      - description: body for Students content
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.CreateStudentRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.UserResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      tags:
      - Students
swagger: "2.0"
